// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_telemetry_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto;
namespace rov {
namespace telemetry {
class telemetry;
struct telemetryDefaultTypeInternal;
extern telemetryDefaultTypeInternal _telemetry_default_instance_;
}  // namespace telemetry
}  // namespace rov
PROTOBUF_NAMESPACE_OPEN
template<> ::rov::telemetry::telemetry* Arena::CreateMaybeMessage<::rov::telemetry::telemetry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rov {
namespace telemetry {

// ===================================================================

class telemetry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rov.telemetry.telemetry) */ {
 public:
  inline telemetry() : telemetry(nullptr) {}
  ~telemetry() override;
  explicit PROTOBUF_CONSTEXPR telemetry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  telemetry(const telemetry& from);
  telemetry(telemetry&& from) noexcept
    : telemetry() {
    *this = ::std::move(from);
  }

  inline telemetry& operator=(const telemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline telemetry& operator=(telemetry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const telemetry& default_instance() {
    return *internal_default_instance();
  }
  static inline const telemetry* internal_default_instance() {
    return reinterpret_cast<const telemetry*>(
               &_telemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(telemetry& a, telemetry& b) {
    a.Swap(&b);
  }
  inline void Swap(telemetry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(telemetry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  telemetry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<telemetry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const telemetry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const telemetry& from) {
    telemetry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(telemetry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rov.telemetry.telemetry";
  }
  protected:
  explicit telemetry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTemperatureFieldNumber = 1,
    kDepthFieldNumber = 2,
  };
  // float temperature = 1;
  void clear_temperature();
  float temperature() const;
  void set_temperature(float value);
  private:
  float _internal_temperature() const;
  void _internal_set_temperature(float value);
  public:

  // float depth = 2;
  void clear_depth();
  float depth() const;
  void set_depth(float value);
  private:
  float _internal_depth() const;
  void _internal_set_depth(float value);
  public:

  // @@protoc_insertion_point(class_scope:rov.telemetry.telemetry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float temperature_;
    float depth_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_telemetry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// telemetry

// float temperature = 1;
inline void telemetry::clear_temperature() {
  _impl_.temperature_ = 0;
}
inline float telemetry::_internal_temperature() const {
  return _impl_.temperature_;
}
inline float telemetry::temperature() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.telemetry.temperature)
  return _internal_temperature();
}
inline void telemetry::_internal_set_temperature(float value) {
  
  _impl_.temperature_ = value;
}
inline void telemetry::set_temperature(float value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.telemetry.temperature)
}

// float depth = 2;
inline void telemetry::clear_depth() {
  _impl_.depth_ = 0;
}
inline float telemetry::_internal_depth() const {
  return _impl_.depth_;
}
inline float telemetry::depth() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.telemetry.depth)
  return _internal_depth();
}
inline void telemetry::_internal_set_depth(float value) {
  
  _impl_.depth_ = value;
}
inline void telemetry::set_depth(float value) {
  _internal_set_depth(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.telemetry.depth)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace telemetry
}  // namespace rov

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
