// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#include "telemetry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rov {
namespace telemetry {
PROTOBUF_CONSTEXPR telemetry::telemetry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.temperature_)*/0
  , /*decltype(_impl_.depth_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct telemetryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR telemetryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~telemetryDefaultTypeInternal() {}
  union {
    telemetry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 telemetryDefaultTypeInternal _telemetry_default_instance_;
}  // namespace telemetry
}  // namespace rov
static ::_pb::Metadata file_level_metadata_telemetry_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_telemetry_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_telemetry_2eproto = nullptr;

const uint32_t TableStruct_telemetry_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rov::telemetry::telemetry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rov::telemetry::telemetry, _impl_.temperature_),
  PROTOBUF_FIELD_OFFSET(::rov::telemetry::telemetry, _impl_.depth_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rov::telemetry::telemetry)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rov::telemetry::_telemetry_default_instance_._instance,
};

const char descriptor_table_protodef_telemetry_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017telemetry.proto\022\rrov.telemetry\"/\n\ttele"
  "metry\022\023\n\013temperature\030\001 \001(\002\022\r\n\005depth\030\002 \001("
  "\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_telemetry_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_telemetry_2eproto = {
    false, false, 89, descriptor_table_protodef_telemetry_2eproto,
    "telemetry.proto",
    &descriptor_table_telemetry_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_telemetry_2eproto::offsets,
    file_level_metadata_telemetry_2eproto, file_level_enum_descriptors_telemetry_2eproto,
    file_level_service_descriptors_telemetry_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_telemetry_2eproto_getter() {
  return &descriptor_table_telemetry_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_telemetry_2eproto(&descriptor_table_telemetry_2eproto);
namespace rov {
namespace telemetry {

// ===================================================================

class telemetry::_Internal {
 public:
};

telemetry::telemetry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rov.telemetry.telemetry)
}
telemetry::telemetry(const telemetry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  telemetry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.temperature_){}
    , decltype(_impl_.depth_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.temperature_, &from._impl_.temperature_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.depth_) -
    reinterpret_cast<char*>(&_impl_.temperature_)) + sizeof(_impl_.depth_));
  // @@protoc_insertion_point(copy_constructor:rov.telemetry.telemetry)
}

inline void telemetry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.temperature_){0}
    , decltype(_impl_.depth_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

telemetry::~telemetry() {
  // @@protoc_insertion_point(destructor:rov.telemetry.telemetry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void telemetry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void telemetry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void telemetry::Clear() {
// @@protoc_insertion_point(message_clear_start:rov.telemetry.telemetry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.temperature_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.depth_) -
      reinterpret_cast<char*>(&_impl_.temperature_)) + sizeof(_impl_.depth_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* telemetry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float temperature = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.temperature_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float depth = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.depth_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* telemetry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rov.telemetry.telemetry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float temperature = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = this->_internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_temperature(), target);
  }

  // float depth = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_depth = this->_internal_depth();
  uint32_t raw_depth;
  memcpy(&raw_depth, &tmp_depth, sizeof(tmp_depth));
  if (raw_depth != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_depth(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rov.telemetry.telemetry)
  return target;
}

size_t telemetry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rov.telemetry.telemetry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float temperature = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = this->_internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    total_size += 1 + 4;
  }

  // float depth = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_depth = this->_internal_depth();
  uint32_t raw_depth;
  memcpy(&raw_depth, &tmp_depth, sizeof(tmp_depth));
  if (raw_depth != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData telemetry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    telemetry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*telemetry::GetClassData() const { return &_class_data_; }


void telemetry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<telemetry*>(&to_msg);
  auto& from = static_cast<const telemetry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rov.telemetry.telemetry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = from._internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    _this->_internal_set_temperature(from._internal_temperature());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_depth = from._internal_depth();
  uint32_t raw_depth;
  memcpy(&raw_depth, &tmp_depth, sizeof(tmp_depth));
  if (raw_depth != 0) {
    _this->_internal_set_depth(from._internal_depth());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void telemetry::CopyFrom(const telemetry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rov.telemetry.telemetry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool telemetry::IsInitialized() const {
  return true;
}

void telemetry::InternalSwap(telemetry* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(telemetry, _impl_.depth_)
      + sizeof(telemetry::_impl_.depth_)
      - PROTOBUF_FIELD_OFFSET(telemetry, _impl_.temperature_)>(
          reinterpret_cast<char*>(&_impl_.temperature_),
          reinterpret_cast<char*>(&other->_impl_.temperature_));
}

::PROTOBUF_NAMESPACE_ID::Metadata telemetry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_telemetry_2eproto_getter, &descriptor_table_telemetry_2eproto_once,
      file_level_metadata_telemetry_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace telemetry
}  // namespace rov
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rov::telemetry::telemetry*
Arena::CreateMaybeMessage< ::rov::telemetry::telemetry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rov::telemetry::telemetry >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
